# Generated by Django 3.2.6 on 2021-08-10 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=320)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('additional_desc', models.TextField(null=True)),
                ('delivery_available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('admin', 'admin'), ('producer', 'producer'), ('customer', 'customer')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Voivodship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.user')),
                ('voivodship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.voivodship')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='additional_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.useradditionalinfo'),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.usertype'),
        ),
    ]
