# Generated by Django 3.2.6 on 2021-08-11 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='district',
            field=models.ForeignKey(default='Not chosen', on_delete=django.db.models.deletion.SET_DEFAULT, to='user_management.district'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='voivodship',
            field=models.ForeignKey(default='Not chosen', on_delete=django.db.models.deletion.SET_DEFAULT, to='user_management.voivodship'),
        ),
    ]
