# Generated by Django 3.2.6 on 2021-08-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20210811_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.useradditionalinfo'),
        ),
        migrations.AlterField(
            model_name='useradditionalinfo',
            name='additional_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('producer', 'Producer'), ('customer', 'Customer')], max_length=8),
        ),
    ]
