# Generated by Django 3.2.6 on 2021-09-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_profile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='profilelocation',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='profilelocation',
            name='city',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='voivodship',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
