# Generated by Django 3.2.6 on 2021-08-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('unposted', 'unposted'), ('unconfirmed', 'unconfirmed'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], max_length=11)),
                ('delivery', models.BooleanField(default=False)),
                ('predicted_delivery_date', models.DateField()),
                ('additional_notes', models.CharField(max_length=300)),
                ('delivery_location', models.ForeignKey(default='Not specified', on_delete=django.db.models.deletion.SET_DEFAULT, to='order_management.deliverylocation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=6)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_management.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.product')),
            ],
        ),
    ]
