# Generated by Django 3.2.6 on 2021-08-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='predicted_delivery',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
