# Generated by Django 3.2.6 on 2021-08-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210829_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='predicted_delivery',
            field=models.DateField(blank=True, null=True),
        ),
    ]
