# Generated by Django 3.2.6 on 2021-09-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_predicted_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverylocation',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='deliverylocation',
            name='city',
            field=models.CharField(max_length=124),
        ),
        migrations.AlterField(
            model_name='deliverylocation',
            name='first_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='deliverylocation',
            name='last_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='add_notes',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
