# Generated by Django 3.2.6 on 2021-09-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210904_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unposted', 'unposted'), ('unconfirmed', 'unconfirmed'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='unposted', max_length=11),
        ),
    ]
